[project]
name = "gaia-multiagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "crewai>=0.65.2",
    "crewai-tools>=0.12.1",
]
